/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.gov.saudecaruaru.bpai.gui;

import br.gov.saudecaruaru.bpai.business.controller.GestorCompetenciaController;
import br.gov.saudecaruaru.bpai.business.model.Diversas;
import br.gov.saudecaruaru.bpai.business.model.GestorCompetencia;
import br.gov.saudecaruaru.bpai.business.model.GestorCompetenciaPK;
import br.gov.saudecaruaru.bpai.business.model.Mes;
import br.gov.saudecaruaru.bpai.gui.documents.AnoDocument;
import br.gov.saudecaruaru.bpai.gui.formatter.MesFormatter;
import br.gov.saudecaruaru.bpai.gui.validators.AnoCompetenciaVerifier;
import com.towel.swing.combo.ObjectComboBoxModel;
import java.awt.Component;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Junior Pires
 */
public class AlteraCompetencia extends javax.swing.JDialog {

    private ObjectComboBoxModel<Mes> objectComboBoxModelMes;
    private GestorCompetenciaController competenciaController;
    private GestorCompetencia competencia;
    /**
     * Creates new form AlteraCompetencia
     */
    public AlteraCompetencia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        myInitComponents();
        
    }
     
    private void initInstances(){
      this.objectComboBoxModelMes= new ObjectComboBoxModel<Mes>();
        
        MesFormatter formatter=new MesFormatter();
        this.objectComboBoxModelMes.setFormatter(formatter);
        
        competenciaController = new GestorCompetenciaController();
        
      
    }
    
    private void myInitComponents(){
        initInstances();
        
        jTextFieldCompetenciaAno.setDocument(new AnoDocument());
        jTextFieldCompetenciaAno.setInputVerifier(new AnoCompetenciaVerifier(this, "Ano"));
        jTextFieldCompetenciaAno.requestFocus();
        initCombobox();
        initValueFields();
    }
    //inicializa a tela em modo critico: a tela só pode ser fechada se a competencia for valida
    public void initCritical(){
        jButtonCompetenciaSair.setEnabled(false);
        this.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }
    
      
 
 public void initValueFields(){
        
        List<GestorCompetencia>  listGc = competenciaController.findAll();
        if(!listGc.isEmpty()){
            String mes = listGc.get(0).getCompetenciaMes();
            String ano = listGc.get(0).getCompetenciaAno();
            
            this.selectItemJComboBoxCompetenciaMes(mes);
            
            
            jTextFieldCompetenciaAno.setText(ano);
        }
    }
    
     private void selectItemJComboBoxCompetenciaMes(String codigoItem){
          Mes m= new Mes(codigoItem, "");   
          this.objectComboBoxModelMes.setSelectedObject(m);
     }

  
    private void initCombobox(){
        objectComboBoxModelMes.setData(Mes.getLIST());
        this.jComboBoxCompetenciaMes.setModel(objectComboBoxModelMes);
        this.jComboBoxCompetenciaMes.setSelectedIndex(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxCompetenciaMes = new javax.swing.JComboBox();
        jTextFieldCompetenciaAno = new javax.swing.JTextField();
        jButtonCompetenciaGravar = new javax.swing.JButton();
        jButtonCompetenciaSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("COMPETÊNCIA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mês");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Ano");

        jComboBoxCompetenciaMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonCompetenciaGravar.setText("Gravar");
        jButtonCompetenciaGravar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCompetenciaGravarMouseClicked(evt);
            }
        });

        jButtonCompetenciaSair.setText("Sair");
        jButtonCompetenciaSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCompetenciaSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxCompetenciaMes, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCompetenciaAno, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonCompetenciaGravar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButtonCompetenciaSair, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxCompetenciaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCompetenciaAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCompetenciaGravar)
                    .addComponent(jButtonCompetenciaSair))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCompetenciaGravarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCompetenciaGravarMouseClicked
        String ano = jTextFieldCompetenciaAno.getText().trim();
        int index = jComboBoxCompetenciaMes.getSelectedIndex();
        
        Mes m = (Mes) objectComboBoxModelMes.getData().get(index);
        String mes = m.getCodigo();
        String competencia = ano+mes;
        
        GestorCompetencia gestorCompetencia = new GestorCompetencia(new GestorCompetenciaPK("1"),competencia);
        
        try {
             competenciaController.merge(gestorCompetencia);
             this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"OCORREU UM ERRO AO TENTAR MUDAR A COMPETÊNCIA", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_jButtonCompetenciaGravarMouseClicked

    private void jButtonCompetenciaSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCompetenciaSairMouseClicked
        if(jButtonCompetenciaSair.isEnabled())
            this.dispose();
    }//GEN-LAST:event_jButtonCompetenciaSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlteraCompetencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlteraCompetencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlteraCompetencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlteraCompetencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AlteraCompetencia dialog = new AlteraCompetencia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCompetenciaGravar;
    private javax.swing.JButton jButtonCompetenciaSair;
    private javax.swing.JComboBox jComboBoxCompetenciaMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldCompetenciaAno;
    // End of variables declaration//GEN-END:variables
}
