/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchGeneric.java
 *
 * Created on 14/08/2012, 14:18:10
 */
package br.gov.saudecaruaru.bpai.gui;

import br.gov.saudecaruaru.bpai.business.controller.BasecController;
import br.gov.saudecaruaru.bpai.business.model.Procedimento;
import br.gov.saudecaruaru.bpai.util.ModelUtil;
import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.WindowConstants;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Albuquerque
 */
public class SearchGeneric extends javax.swing.JDialog {
    
    private Serializable model= new Procedimento();
    private String fieldId= "";
    private String fieldDescription="";
    private String[] header=new String[]{"Código","Descrição"};
    private String result="NOTHING";
    
    public static SearchGeneric instance=null;
    
    private BasecController basicController=null;

    /** Creates new form SearchGeneric */
    private SearchGeneric() {
        initComponents();
        this.initTable();
        this.initLookAndFeel();
        this.initTextFieldSearch();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLista = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setForeground(java.awt.Color.white);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setText("Selecionar por:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jTextField1.setToolTipText("");
        jTextField1.setName("textFieldPesquisa"); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Pesquisar(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel2.setText("Pesquisar");
        jLabel2.setName("lbl_pesquisa"); // NOI18N

        tableLista.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tableLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableLista.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableLista.setEditingColumn(1);
        tableLista.setEditingRow(1);
        tableLista.setName("tableLista"); // NOI18N
        tableLista.setOpaque(false);
        tableLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableLista);
        tableLista.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                            .addGap(182, 182, 182)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Pesquisar(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Pesquisar

        System.out.println(evt.getKeyCode());
        System.out.println(evt.getKeyChar());
    }//GEN-LAST:event_Pesquisar

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        //clicou em esc
        if(evt.getKeyCode()==27){
            //vai fechar a tela
            this.result="";
            this.dispose();
            
        }
        //clicou em f2
        else if(evt.getKeyCode()==113){
            this.result=this.getValueItemSelected();
            if(this.result!=null){
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(this, "Não existe linha selecionada na tabela!");
            }
        }
    }//GEN-LAST:event_formKeyPressed

    private void tableListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListaMouseClicked
        
        if(evt.getClickCount()==2){
            this.result=this.getValueItemSelected();
            if(this.result!=null){
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(this, "Não existe linha selecionada na tabela!");
            }
        }
        
        
    }//GEN-LAST:event_tableListaMouseClicked
    //realiza  a busca caso o usuário digite algum caractere válido
    private void initTextFieldSearch(){
        this.jTextField1.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                if(SearchGeneric.this.jTextField1.getText().length()>4){
                    SearchGeneric.this.updateTable(SearchGeneric.this.search());
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }
        });
    }
    private void initTable(){
        this.tableLista.getColumnModel().getColumn(0).setPreferredWidth(150);
        this.tableLista.getColumnModel().getColumn(1).setPreferredWidth(600);
        this.tableLista.setRowSelectionAllowed(true);
	this.tableLista.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       //this.tableLista.getModel().
    }
    
    
    
    public static SearchGeneric getInstance(){
        if(SearchGeneric.instance==null){
            SearchGeneric.instance= new SearchGeneric();
        }
        return SearchGeneric.instance;
    }
    
    public String initModeSearch(BasecController controller,String fieldId,String FieldDescription, String labelFieldId,String labelFieldDescription){
        this.header[0]=labelFieldId;
        this.header[1]=labelFieldDescription;
        ComboBoxModel model=new DefaultComboBoxModel(new String[]{labelFieldDescription,labelFieldId});
        this.fieldDescription=FieldDescription;
        this.fieldId=fieldId;
        this.basicController=controller;
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        this.jComboBox1.setModel(model);
        this.tableLista.setModel(new DefaultTableModel(null,this.header));
        this.initTable();
        this.setModal(true);
        this.setVisible(true);
        return this.result;
    }
    
    private void updateTable(String[][] rows){
        DefaultTableModel modelo = new DefaultTableModel(rows,this.header);
	this.tableLista.setModel(modelo);
        this.initTable();
        
    }
    
    private String getValueItemSelected(){
        return null;
    }
    
    private String[][] search(){
        //cria um map para montar as restrições
        Map<String, Object> res= new HashMap<String, Object>();
        //faz a busca de acordo com o campo escolhido no cambobox
        if(this.jComboBox1.getSelectedItem().toString().equals(this.header[0])){
           res.put(this.fieldId, this.jTextField1.getText().toUpperCase());
        }
        else{
           res.put(this.fieldDescription, this.jTextField1.getText().toUpperCase());
        }
        //faz a busca
        List l=this.basicController.findAllLike(res);
        if(l==null);
        //pega um map onde  a chave representa o chave primária do modelo e o value a uma descrição
        Map<String,String> datas = ModelUtil.getMapSearch(l,this.fieldId,this.fieldDescription);

        //cria a matriz de dados
        String[][] rows= new String[datas.size()][this.header.length];
        if(datas!=null){
            int i=0;
            for(String key: datas.keySet()){
                rows[i][0]=key;
                rows[i][1]=datas.get(key);
                i++;
            }
        }
        return rows;
    }
    private void initLookAndFeel(){
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchGeneric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchGeneric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchGeneric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchGeneric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SearchGeneric().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tableLista;
    // End of variables declaration//GEN-END:variables
}
